<a href="https://colab.research.google.com/github/Aaryant31/Hotel-Booking-Analysis/blob/main/Rahul_kr_Soni__Hotel_Booking_Analysis_Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## <b> Have you ever wondered when the best time of year to book a hotel room is? Or the optimal length of stay in order to get the best daily rate? What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests? This hotel booking dataset can help you explore those questions!

## <b>This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally identifying information has been removed from the data. </b>

## <b> Explore and analyze the data to discover important factors that govern the bookings. </b>

In [1]:
#importing Librabries

import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
#importing Dataset from github url

url = "https://raw.githubusercontent.com/Aaryant31/Hotel-Booking-Analysis/main/Hotel%20Bookings.csv"
df =pd.read_csv(url)

In [26]:
#veiwing head of Dataframe

df.head()

hotel  is_canceled  ...  reservation_status  reservation_status_date
0  Resort Hotel            0  ...           Check-Out               2015-07-01
1  Resort Hotel            0  ...           Check-Out               2015-07-01
2  Resort Hotel            0  ...           Check-Out               2015-07-02
3  Resort Hotel            0  ...           Check-Out               2015-07-02
4  Resort Hotel            0  ...           Check-Out               2015-07-03

[5 rows x 32 columns]

In [27]:
#checking Shape of Dataframe

df.shape

(119390, 32)

In [29]:
#checking columns of dataframe
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [30]:
#checking informatiom of dataframe

hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119390 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [32]:
#checking for null values
df.isna().sum().sort_values(ascending=False)



company                           112593
agent                              16340
country                              488
children                               4
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
is_canceled                            0
market_segment                         0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
babies                                 0
meal                                   0
reservation_status_date                0
distribution_channel                   0
reservation_status                     0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes 

In [33]:
#Replacing NUll value with zero for convinience

df.fillna(0, inplace=True)

In [34]:
#again checking for null value
df.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                         

**Now we can see there is no null value in hotel Dataframe**

In [35]:
#checking value of children
df['children'].unique()

array([ 0.,  1.,  2., 10.,  3.])

In [36]:
#checking value of adults
df['adults'].unique()

array([ 2,  1,  3,  4, 40, 26, 50, 27, 55,  0, 20,  6,  5, 10])

In [37]:
#checking value of adults
df['babies'].unique()

array([ 0,  1,  2, 10,  9])

# **From the above data we can say that adults, childrens and babies can't be zero at a time**

In [38]:
# so now we are going to filter data where value of adults, children and babies = 0

checking_value_0_of_ad_ch_baby = (hotel_df['adults']==0) & (hotel_df['children']==0) & (hotel_df['babies']==0)

# reading data frame where adult,children and babies are 0
df[checking_value_0_of_ad_ch_baby]

hotel  is_canceled  ...  reservation_status  reservation_status_date
2224    Resort Hotel            0  ...           Check-Out               2015-10-06
2409    Resort Hotel            0  ...           Check-Out               2015-10-12
3181    Resort Hotel            0  ...           Check-Out               2015-11-23
3684    Resort Hotel            0  ...           Check-Out               2016-01-04
3708    Resort Hotel            0  ...           Check-Out               2016-01-05
...              ...          ...  ...                 ...                      ...
115029    City Hotel            0  ...           Check-Out               2017-06-30
115091    City Hotel            0  ...           Check-Out               2017-07-01
116251    City Hotel            0  ...           Check-Out               2017-07-17
116534    City Hotel            0  ...           Check-Out               2017-07-22
117087    City Hotel            0  ...           Check-Out               2017-07-29

[180 rows x 32 columns]

 As we know  adult, children and babies can't be zero at a time that means these are wrong input so we have to remove this data 

In [41]:
#reading and storing data where adults,children and babies are having non 0 value 

hotel_df=df[~checking_value_0_of_ad_ch_baby]

In [42]:
# reading hotel_df dataframe
hotel_df

hotel  is_canceled  ...  reservation_status  reservation_status_date
0       Resort Hotel            0  ...           Check-Out               2015-07-01
1       Resort Hotel            0  ...           Check-Out               2015-07-01
2       Resort Hotel            0  ...           Check-Out               2015-07-02
3       Resort Hotel            0  ...           Check-Out               2015-07-02
4       Resort Hotel            0  ...           Check-Out               2015-07-03
...              ...          ...  ...                 ...                      ...
119385    City Hotel            0  ...           Check-Out               2017-09-06
119386    City Hotel            0  ...           Check-Out               2017-09-07
119387    City Hotel            0  ...           Check-Out               2017-09-07
119388    City Hotel            0  ...           Check-Out               2017-09-07
119389    City Hotel            0  ...           Check-Out               2017-09-07

[119210 rows x 32 columns]